name: run_sutom_daily
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  copute_daily_sutom:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: '0'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright
    - name: Run everything in the same step
      run: |
        sudo apt update
        sudo apt install curl -y
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk install jbang
        xvfb-run jbang Sutom.java --mastodon-access-token ${{ secrets.MASTODON_ACCESS_TOKEN }} --mastodon-server-host-name ${{ secrets.MASTODON_SERVER_HOST_NAME }}
