name: run_sutom_daily
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  run_sutom_bot:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: '0'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
        cache: 'maven'
    - name: Run everything in the same step
      run: |
        sudo apt update
        sudo apt install curl -y
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk help
        sdk install jbang
        jbang --help
        xvfb-run jbang Sutom.java
